#### What is the purpose of Python's OOP?
- purpose of Python's OOP is structuring a program by bundling related properties and behaviors into individual objects.
- OOP is about code reuse 
-  minimize redundancy and program by customizing what already exists instead of changing code in place or starting from scratch


#### Q2. Where does an inheritance search look for an attribute?

- An inheritance search looks for an attribute first in the instance object,
- then in the class the instance was created from, then in all higher superclasses,
- progressing from left to right (by default). The search stops at the first place the attribute is found



#### Q3. How do you distinguish between a class object and an instance object?

class:
    - A class is a template for creating objects in program.
    - A class does not allocate memory space when it is created.
object:
    - The object is an instance of a class.
    - Object allocates memory space whenever they are created.



#### Q4. What makes the first argument in a class’s method function special?

- The first argument of every class method, including init, is always a reference to the current instance of the class. 
- By convention, this argument is always named self.
- In the init method, self refers to the newly created object;
- in other class methods, it refers to the instance whose method was called.



#### Q5. What is the purpose of the __init__ method?

- The __init__ method is the Python equivalent of the C++ constructor in an object-oriented approach.
- The __init__  function is called every time an object is created from a class.
- The __init__ method lets the class initialize the object’s attributes and serves no other purpose.
- It is only used within classes



#### Q6. What is the process for creating a class instance?

- Call ClassName() to create a new instance of the class ClassName . 
- To pass parameters to the class instance, the class must have an __init__() method.
- Pass the parameters in the constructor of the class.




#### Q7. What is the process for creating a class?


- to create a class use the keyword class


#### Q8. How would you define the superclasses of a class?

- A superclass is the class from which many subclasses can be created. The subclasses inherit the characteristics of a superclass. 
- The superclass is also known as the parent class or base class
- The super() function is used to give access to methods and properties of a parent or sibling class.

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b=a[:2,1:4]

In [8]:
b

array([[2, 3],
       [5, 6]])